# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a2c0cb9a24e7d2f8bdb25c80c0d65be1a47949c43818d0d92157022475ec8cf7084fb6dbf21500139801f96292668c901dc9c0f416d5280140dd06acdf168db

test:
  secret_key_base: 3070bb21ae3d63de8cd0f048853399acaee893e2a3bc7f6ebd38e05377116140bc19d1b2732ceb3dfdfb4d77a3f0e75c9e06be0565e8a601f07de42c5b32a9f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
